host, mmcomm.qpic.cn, reject
host, v.didi.cn, reject-img
host, img-hxy021.didistatic.com, reject-img
host, shop-gw.chengxinyouxuan.com, reject-img
host, img-ys011.didistatic.com, rejec-img
host, msgacs.m.taobao.com, reject-img
host-keyword, mobiledispatch, reject
host, restapi.amap.com, reject
host, adashx.m.taobao.com, reject
host, h-adashx.ut.taobao.com, reject
host, iyes.youku.com, reject
host, sns.amap.com, reject
host, optimus-ads.amap.com, reject
host, wap.barpsi.com, reject
host, sldy.whcon.cn, reject
host, mtop.cainiao.guoguo.nbnetflow.ads.show, reject
host, dorangesource.alicdn.com, reject
host, ossgw.alicdn.com, reject
host, zconfig.alibabausercontent.com, reject
host, acs.m.taobao.com, reject
host, sf3-fe-tos.pglstatp-toutiao.com, reject
host, *.pglstatp-toutiao.com, reject
host, hmma.baidu.com, reject
host, mmap-mobile-lbsapp.cdn.bcebos.com, reject
host, map-mobile-resource.su.bcebos.com, reject
host, newclient.map.baidu.com, reject
host, rich.kuwo.cn, reject
host, pgdt.gtimg.cn, reject
host, wn.pos.baidu.com, reject
host, cpro.baidustatic.com, reject
host, luimg.baidu.com, reject
host, ad.adsrvr.org, reject
#host, ios-dc.51y5.net, reject
host, v6.onewsvod.com, reject
host, v1.onewsvod.com, reject
host, open.toutiao.com, reject
host, cmt.lsttnews.com, reject
host, ia1.wifi188.com, reject
host, mess-lab.com, reject
host, rbv01.ku6.com, reject
host, d.wifi188.com, reject
host, jump.9118ads.com, reject
host, us.l.qq.com, reject
host, m.app.so.com, reject
host-suffix, m.so.com, reject
host, m.360.cn, reject
host-suffix, 360.cn, reject
user-agent, 360*, reject
host, pt-starimg.didistatic.com, reject
host, img-ys011.didistatic.com, reject
host, ad.caiyunapp.com, reject
host, sdk.1rtb.com, reject
host, *.360buyimg.com, reject
host, api-access.pangolin-sdk-toutiao.com, reject
host, *.ugdtimg.com, reject
host, iadmat.nosdn.127.net, reject
host, admusicpic.music.126.net, reject
host, *.unsplash.com, proxy
host-suffix, huawei.com, reject
host-keyword, huawei, reject
