host, kwimg3.kuwo.cn, reject
host, adstats.tencentmusic.com, reject
host, free-mapdownload.autonavi.com, reject
//host, receiptcheck.quantumult.app, reject
host, p44-acsegateway.icloud.com.cn, reject
-host, optimus-ads.amap.com, reject
host, aos-cdn-image.amap.com, reject
host, gw.alicdn.com, reject
-host, poi.map.xiaojukeji.com, reject
host, img-hxy021.didistatic.com, reject
host, img-ys011.didistatic.com, reject
host, shop-gw.chengxinyouxuan.com, reject
host, adtrack.xiaojukeji.com, reject
host, sf6-be-pack.pglstatp-toutiao.com, reject
host, s3gw.cmbimg.com, reject
host-suffix, baidubce.com, direct
host-suffix, savieo.com, proxy
host, shouji.360.cn, reject
host, cds.wifi188.com, reject
host, appgo.189.cn, reject
host, xbk.189.cn, reject
host, api.share.mob.com, direct
host-suffix, jgsjtj.189.cn, reject
host-suffix, myqcloud.com, reject
host, image1.chinatelecom-ec.com, reject
host-suffix, api.mixpanel.com, direct
user-agent, AVOS*, reject
host, sugar.zhihu.com, reject
host, mqtt.zhihu.com, reject
host, appcloud2.in.zhihu.com, reject
ip6-cidr, 2402:4e00:1200:ed00:0:9089:6dac:96b6/128, reject
ip-cidr, 118.89.204.198/32, reject
host, 118.89.204.198, reject
host, res.maka.im, reject
host, adssettings.google.com, reject
host, pagead2.googlesyndication.com, reject
host, restapi.amap.com, direct
host, fanyi-api.baidu.com, direct
host, kepler.jd.com, direct
host, btrace.qq.com, direct
host, ei.phncdn.com, proxy
host, e.189.cn, direct
-host, tt-ugc-cdnqn.52tt.com, reject
host, sf6-be-pack.pglstatp-toutiao.com, reject
host, sf3-be-pack.pglstatp-toutiao.com, reject
host, p.pstatp.com, reject
host, baichuan-sdk.alicdn.com, reject
host, m.360buyimg.com, direct
host, api-access.pangolin-sdk-toutiao-b.com, reject
host, kepler.jd.com, reject
host, mmcomm.qpic.cn, reject
host, v.didi.cn, reject-img
host, img-hxy021.didistatic.com, reject-img
host, shop-gw.chengxinyouxuan.com, reject-img
host, img-ys011.didistatic.com, rejec-img
host, msgacs.m.taobao.com, reject-img
host-keyword, mobiledispatch, reject
host, restapi.amap.com, reject
host, adashx.m.taobao.com, reject
host, h-adashx.ut.taobao.com, reject
host, iyes.youku.com, reject
host, sns.amap.com, reject
host, optimus-ads.amap.com, reject
host, wap.barpsi.com, reject
host, sldy.whcon.cn, reject
host, mtop.cainiao.guoguo.nbnetflow.ads.show, reject
host, dorangesource.alicdn.com, reject
host, ossgw.alicdn.com, reject
host, zconfig.alibabausercontent.com, reject
host, acs.m.taobao.com, reject
host, sf3-fe-tos.pglstatp-toutiao.com, reject
host, *.pglstatp-toutiao.com, reject
host, hmma.baidu.com, reject
host, mmap-mobile-lbsapp.cdn.bcebos.com, reject
host, map-mobile-resource.su.bcebos.com, reject
host, newclient.map.baidu.com, reject
host, rich.kuwo.cn, reject
host, pgdt.gtimg.cn, reject
host, wn.pos.baidu.com, reject
host, cpro.baidustatic.com, reject
host, luimg.baidu.com, reject
host, ad.adsrvr.org, reject
host, v6.onewsvod.com, reject
host, v1.onewsvod.com, reject
host, open.toutiao.com, reject
host, cmt.lsttnews.com, reject
host, ia1.wifi188.com, reject
host, mess-lab.com, reject
host, rbv01.ku6.com, reject
host, d.wifi188.com, reject
host, jump.9118ads.com, reject
host, us.l.qq.com, reject
host, m.app.so.com, reject
host-suffix, m.so.com, reject
host, m.360.cn, reject
host-suffix, 360.cn, reject
user-agent, 360*, reject
host, pt-starimg.didistatic.com, reject
host, img-ys011.didistatic.com, reject
host, ad.caiyunapp.com, reject
host, sdk.1rtb.com, reject
host, *.360buyimg.com, reject
host, api-access.pangolin-sdk-toutiao.com, reject
host, *.ugdtimg.com, reject
host, iadmat.nosdn.127.net, reject
host, admusicpic.music.126.net, reject
host, *.unsplash.com, proxy
host-suffix, huawei.com, reject
host-keyword, huawei, reject
